---
title: "logicals"
author: "Charles Hendrickson"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Taking a look at `starwars` 

- `include =` :show or hide everything 
- `echo =` :show or hide code 

```{r, echo = FALSE}

# Summary of starwars 
summary(starwars)

# Look at the first few lines 
head(starwars)

# Look at the dimensions 
dim(starwars)

```


```{r, warning = FALSE }
ggplot(data = starwars, aes(x = height, y = mass)) + 
  geom_point(color = "purple")
```

## Find the mean, variance and SD of character height 

```{r}
sw_height_mean <- mean(starwars$height, na.rm = FALSE)
sw_height_mean

# Run as true if there are NA in the data set
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_mean

# Using similar naming system, find:
# Variance of character height (var())
# Standard deviation of character height (sd())

sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_var

sw_height_sd <- sd(starwars$height, na.rm = TRUE)
sw_height_sd

```

# This is not reproducable 
Mean character height is 174.4cm with a standard deviation of 34.8 cm. 

Mean character height is `r round(sw_height_mean, 1)`cm, with a standard deviation of `r round(sw_height_sd, 1)` cm. 

## Logical expressions 

```{r}
5 < 10 

"cat" > "armadillo"

"cat" > "elephant"
```

```{r}
t <- c(1,3,7,10,15)

t > 5
```

## Logical operators 
- `!`
- `&`
- `|`

```{r}
3 < 1 | 8 > 2

6 < 10 & 5 < 1 

7 != 4 | 2 < 5 | 6 > 10

0 == FALSE

1 == TRUE








```

